"""Update models with validation fields

Revision ID: 1796f90b9bb0
Revises: fea483778e36
Create Date: 2025-08-16 18:20:15.672602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1796f90b9bb0'
down_revision: Union[str, Sequence[str], None] = 'fea483778e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(), nullable=True))
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    op.drop_column('project', 'name')
    op.add_column('task', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    op.drop_column('task', 'is_completed')
    op.add_column('project', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
